### PR TITLE
[Bug]: HTML output of Table is missing colgroup element

### LINKED ISSUE #4280: [Bug]: HTML output of Table is missing colgroup element
### Which packages did you experience the bug in?

extension-table

### What Tiptap version are you using?

2.0.4

### What’s the bug you are facing?

When using resizable Table, table columns can be resized. This is working with editor. When outputing html from editor
using e.g. `editor.getHTML()` or `generateHTML`, rendered table is not including required `colgroup` element.

### What browser are you using?

Chrome

### Code example

_No response_

### What did you expect to happen?

I'm expecting rendered html to include `colgroup` element.

### Anything to add? (optional)

I will try to create pull request with fix.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

### PR DESCRIPTION
**Pull request by diginikkari**
Fixes #4280

## Please describe your changes

Added createColGroup function to generate colGroup based on child nodes (imitates `updateColumns` which is used for editor TableView.

## How did you accomplish your changes

`renderHTML` is calling `updateColumns` to get generated `colgroup` element, `tableWidth` and `tableMinWidth` values.

## How have you tested your changes

Updated *react* and *vue* e2e tests to assert that there is `colgroup` -element.

## How can we verify your changes

[add a detailed description of how we can verify your changes here]

## Remarks

[add any additional remarks here]

## Checklist

- [x] The changes are not breaking the editor
- [x] Added tests where possible
- [x] Followed the guidelines
- [x] Fixed linting issues

## Related issues

#721

### CODE REVIEW

File: packages/extension-table/src/utilities/createColGroup.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+
+export function createColGroup(
+  node: ProseMirrorNode,
+  cellMinWidth: number,
+  overrideCol?: number,
+  overrideValue?: any,
+) {
+  let totalWidth = 0
+  let fixedWidth = true
+  const colls: DOMOutputSpec[] = []
```
Comment (bdbch) [inline packages/extension-table/src/utilities/createColGroup.ts:12]: Typo: `colls` => `cols`

**Review by bdbch — CHANGES_REQUESTED** [review]

**Review by bdbch — APPROVED** [review]

**Comment by diginikkari** [comment]
@bdbch any change to get this merged any time soon?

File: packages/extension-table/src/table.ts [hunk 2]
```diff
@@ -110,8 +112,24 @@ export const Table = Node.create<TableOptions>({
...
+      node,
+      this.options.cellMinWidth,
+    )
+
+    const table: DOMOutputSpec = [
+      'table',
+      mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
+        style: tableWidth
+          ? `width: ${tableWidth}`
+          : `minWidth: ${tableMinWidth}`,
```
Comment (iowxy) [inline packages/extension-table/src/table.ts:126]: minWidth or `min-width` ?
