### PR TITLE
fix: parse mixed bullet lists and task lists correctly

### LINKED ISSUE #7093: Markdown gets incorrectly parsed
### Affected Packages

react, markdown, extension-list

### Version(s)

3.7.2

### Bug Description

When using the `@tiptap/markdown` package, the markdown doesn't get properly parsed when using check lists.

**Examples:**

1. When writing a check list item `- [ ] todo 1` it converts it strangely and adds extra characters:

Image

Image

2. When having a list and then a checklist item right after it, it removes the checklist item:

Image

Image

### Browser Used

Chrome

### Code Example URL

https://stackblitz.com/edit/vitejs-vite-r8cpsk5l?file=src%2FMarkdownEditor.tsx

### Expected Behavior

The checklist should be properly parsed, and different list types should be accepted, like in the markedjs extension demo.

### Additional Context (Optional)

_No response_

### Dependency Updates

- [x] Yes, I've updated all my dependencies.

### PR DESCRIPTION
**Pull request by bdbch**
## Changes Overview

- **Fixed mixed list parsing**: Marked.js groups consecutive bullet list items and task list items into a single list token, causing incorrect parsing. Added special handling to detect and split mixed lists into separate `bulletList` and `taskList` nodes.
- **Fixed nested content parsing in task items**: Task items with nested content (headings, paragraphs, nested lists) were not parsing correctly. Used full Marked.js lexer pipeline to ensure inline tokens are populated for headings and other block elements.
- **Refactored utility function**: Moved `isTaskItem` from `MarkdownManager` class to utils.ts for better separation of concerns and reusability.
- **Added comprehensive test**: Created test case for mixed list types conversion to ensure the fix works correctly.

## Implementation Approach

The core issue was that Marked.js's default tokenizer groups consecutive list items of different types (bullet vs task) into a single list token. The solution:

1. **Intercept list tokens** in `parseToken()` and route them to specialized `parseListToken()` method
2. **Detect mixed lists** by checking if the list contains both task items and regular bullet items
3. **Split into groups** by iterating through items and grouping consecutive items by type
4. **Transform task items** into custom tokens with proper nested content parsing using `markedInstance.lexer()` instead of `lexer.blockTokens()` to ensure inline tokens are populated
5. **Parse each group separately** as individual list/taskList tokens

The nested content fix was critical - using `markedInstance.lexer()` runs the full tokenization pipeline including inline token processing, which `lexer.blockTokens()` skips.

## Testing Done

- **Added new test case**: mixed-list-types.ts tests conversion between markdown and JSON for mixed bullet/task lists
- **All existing tests pass**: 18/18 tests passing in the markdown conversion test suite
- **Manual testing**: Verified with demo content containing nested task items with headings
- **Round-trip testing**: Ensured markdown → JSON → markdown conversion works correctly

## Verification Steps

1. **Test mixed lists**: Create markdown with consecutive bullet and task list items:
   ```
   - Bullet item
   
   - [ ] Task item 1
   - [ ] Task item 2
   ```
   Should parse into separate `bulletList` and `taskList` nodes.

2. **Test nested content**: Create task item with heading:
   ```
   - [ ] Task with nested content
     ## Heading
     Paragraph
   ```
   Heading should render with proper text content, not as `<h2><br class="ProseMirror-trailingBreak"></h2>`.

3. **Run tests**: `pnpm test:run --project tests --spec "**conversion.spec.ts"` - all 18 tests should pass.

## Additional Notes

The fix is backward compatible and only activates when:
- TaskList extension is registered
- A list token contains both task and non-task items

The `isTaskItem` utility function was moved to utils.ts for better code organization and potential reuse in other parts of the codebase.

## Checklist

- [x] I have created a [changeset](https://github.com/changesets/changesets) for this PR if necessary.
- [x] My changes do not break the library.
- [x] I have added tests where applicable.
- [x] I have followed the project guidelines.
- [x] I have fixed any lint issues.

## Related Issues

Fixes #7093 - Mixed bullet lists and task lists parsing incorrectly

### CODE REVIEW

File: tests/cypress/integration/markdown/conversion-files/mixed-list-types.ts
Comment (arnaugomez) [inline tests/cypress/integration/markdown/conversion-files/mixed-list-types.ts:1]: These tests don't have to be integration tests with Cypress, right? We could use Vitest for these tests, which runs faster because it does not need a browser environment.

File: packages/markdown/src/utils.ts [hunk 1]
```diff
@@ -133,6 +133,28 @@ export function reopenMarksAfterNode(
...
+ * @example
+ * ```ts
+ * isTaskItem({ raw: '- [ ] Task' }) // { isTask: true, checked: false, indentLevel: 0 }
+ * isTaskItem({ raw: '  - [x] Done' }) // { isTask: true, checked: true, indentLevel: 2 }
+ * isTaskItem({ raw: '- Regular' }) // { isTask: false, indentLevel: 0 }
+ * ```
+ */
+export function isTaskItem(item: any): { isTask: boolean; checked?: boolean; indentLevel: number } {
+  const raw = item.raw || item.text || ''
+  const match = raw.match(/^(\s*)[-+*]\s+\[([ xX])\]\s+/)
```
Comment (arnaugomez) [inline packages/markdown/src/utils.ts:153]: When you have a long regex, add a comment explaining what it matches

**Review by arnaugomez — APPROVED** [review]
LGTM but I'd have a look at @copilot 's suggestions, especially the ones that refer to type safety.

**Comment by arnaugomez** [comment]
> @arnaugomez I've opened a new pull request, #7179, to work on those changes. Once the pull request is ready, I'll request review from you.

noo what? I didn't ask you that

File: tests/cypress/integration/markdown/conversion-files/mixed-list-types.ts
Comment (bdbch) [reply tests/cypress/integration/markdown/conversion-files/mixed-list-types.ts:1]: Yes, but we don't have Vitest integrated yet on the OSS side so we still use Cypress here.

**Comment by bdbch** [comment]
> > @arnaugomez I've opened a new pull request, #7179, to work on those changes. Once the pull request is ready, I'll request review from you.
> 
> noo what? I didn't ask you that

you mentioned it haha
