### PR TITLE
fix: preserve lazy continuation lines in ordered lists (CommonMark)

### LINKED ISSUE #7677: OrderedList markdownTokenizer drops lazy continuation lines (CommonMark)
## Bug Description

The `collectOrderedListItems` function in `@tiptap/extension-list` (v3.20.6) incorrectly terminates a list item when encountering a non-indented continuation line. Per [CommonMark spec §5.3](https://spec.commonmark.org/0.31.2/#list-items), non-indented lines following a list item marker **without** a preceding blank line are "lazy continuation lines" and should be treated as part of the current list item.

## Steps to Reproduce

Configure the editor with `Markdown.configure({ markedOptions: { breaks: true } })` and feed it this markdown:

```markdown
1. De fiets op de vennootschap
Dit is meestal het interessantst. De vennootschap trekt de aankoop af.

2. De fiets privé gekocht
Heb je de fiets privé betaald? Dan kan je vennootschap jou een fietsvergoeding betalen.
```

## Expected Behavior

Each list item should render with its full continuation text:

```html
<ol>
  <li><p>De fiets op de vennootschap<br>Dit is meestal het interessantst. De vennootschap trekt de aankoop af.</p></li>
  <li><p>De fiets privé gekocht<br>Heb je de fiets privé betaald? Dan kan je vennootschap jou een fietsvergoeding betalen.</p></li>
</ol>
```

## Actual Behavior

Only the first line of each list item is rendered. The continuation text is dropped entirely:

```html
<ol><li><p>De fiets op de vennootschap</p></li></ol>
<p><br></p>
<ol start="2"><li><p>De fiets privé gekocht</p></li></ol>
```

## Root Cause

In [`src/ordered-list/utils.ts` — `collectOrderedListItems`](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-list/src/ordered-list/utils.ts), the inner while loop has:

```typescript
} else {
  // Non-indented line means end of list
  break
}
```

This unconditionally breaks on any non-indented, non-empty, non-list-item line — but CommonMark allows "lazy continuation" where non-indented text **before** a blank line is still part of the current list item.

Additionally, `buildNestedStructure` only uses `contentLines[0]` as the paragraph text and sends the rest through `lexer.blockTokens()`, which loses inline break handling when `breaks: true` is configured.

## Suggested Fix

**`collectOrderedListItems`:** Track whether a blank line has been seen (`sawBlankLine`). Non-indented text before a blank line → lazy continuation (append to current item). After a blank line → break.

**`buildNestedStructure`:** Collect all lines before the first blank line into a single paragraph token using `lexer.inlineTokens()` (so `breaks: true` produces `hardBreak` nodes), then process lines after the blank line as block tokens.

## Environment

- `@tiptap/extension-list`: 3.20.6
- `@tiptap/markdown`: 3.20.6
- `@tiptap/starter-kit`: 3.20.6

### PR DESCRIPTION
**Pull request by bdbch**
## Changes Overview

Fix ordered-list markdown parsing so non-indented lazy continuation lines are kept as part of the current list item (CommonMark §5.3). This prevents continuation text from being dropped when `marked` is configured with `breaks: true` and preserves nested list behavior.

## Implementation Approach

- Updated `collectOrderedListItems` in `packages/extension-list/src/ordered-list/utils.ts` to track whether a blank line has been seen and treat non-indented, non-list lines before a blank line as "lazy continuation" belonging to the current list item.
- Added `contentLines` on `OrderedListItem`, `splitItemContent()`, and `isBlockContentLine()` helpers to separate paragraph (inline) lines from block-level lines.
- Updated `buildNestedStructure()` to create the first paragraph using `lexer.inlineTokens()` for the joined paragraph lines (so `breaks: true` produces `hardBreak` tokens), and to parse later block content through `lexer.blockTokens()` so nested lists / block nodes remain intact.
- Added a focused regression test `packages/markdown/__tests__/ordered-list-lazy-continuation.spec.ts` that runs with `markedOptions: { breaks: true }` and verifies lazy continuation, nested bullet preservation, and blank-line termination.
- Added a changeset: `.changeset/ordered-list-lazy-continuation.md`.

## Testing Done

- Ran the new focused spec: `pnpm vitest run packages/markdown/__tests__/ordered-list-lazy-continuation.spec.ts` — all tests passed.
- Ran the markdown conversion suite: `pnpm vitest run packages/markdown/__tests__/conversion.spec.ts` — all tests passed.
- Verified the repository commit includes the changeset and tests.

## Verification Steps

- Checkout branch: `git fetch && git checkout fix/ordered-list-lazy-continuation`
- Run the focused spec:

```bash
pnpm vitest run packages/markdown/__tests__/ordered-list-lazy-continuation.spec.ts
```

- Run the markdown conversion suite to ensure no regressions:

```bash
pnpm vitest run packages/markdown/__tests__/conversion.spec.ts
```

## Additional Notes

- The change keeps blank-line semantics intact: a non-indented continuation line before a blank line is part of the previous list item; a non-indented line after a blank line terminates the list.
- The fix is intentionally conservative: paragraph (inline) lines are tokenized with `inlineTokens()` to preserve `hardBreak` nodes when `breaks: true`, while later block content is parsed via `blockTokens()` to retain nested lists and block nodes.

## Checklist

- [x] I have created a changeset for this PR.
- [x] My changes do not break the library (local markdown tests passed).
- [x] I have added tests where applicable.
- [x] I have followed the project guidelines.
- [x] I have fixed any lint issues.

## Related Issues

Fixes: #7677

### CODE REVIEW

**Review by arnaugomez — APPROVED** [review]

File: packages/extension-list/src/ordered-list/utils.ts [hunk 1]
```diff
@@ -20,9 +20,57 @@ export interface OrderedListItem {
...
+  const trimmedLine = line.trimStart()
+
+  return (
+    /^[-+*]\s+/.test(trimmedLine) ||
+    /^\d+\.\s+/.test(trimmedLine) ||
+    /^>\s?/.test(trimmedLine) ||
+    /^```/.test(trimmedLine) ||
+    /^~~~/.test(trimmedLine)
+  )
+}
```
Comment (arnaugomez) [inline packages/extension-list/src/ordered-list/utils.ts:37]: Could there be other block content elements that are not covered here?
