### PR TITLE
fix(core): InputRules does not work for ranges containing multiple text nodes

### LINKED ISSUE #3071: InputRules does not work for ranges containing multiple text nodes.
### What’s the bug you are facing?

When markdown tags cover multiple text nodes, they will not work. See GIF:

动画

The initial problem was #2937, fixed by #2941.

But if a paragraph contains multiple text nodes within it, and InputRule needs to span those nodes, it will not work.

I'm using the latest code from the main branch.

### Which browser was this experienced in? Are any special extensions installed?

Chrome/103.0.0.0. No special extensions.

### How can we reproduce the bug on our side?

1. type 'A   B   C'
2. make 'B' bold
3. type '*' at the begining
4. type '*' at the end

correct result: *A **B** C*
incorrect result: \*A **B** C\*

### Can you provide a CodeSandbox?

No CodeSandbox, but there is a "Deploy Preview" provided by #2941

<https://deploy-preview-2941--tiptap-embed.netlify.app/>

### What did you expect to happen?

InputRule should work between multiple text nodes.

### Anything to add? (optional)

_No response_

### Did you update your dependencies?

- [x] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

### PR DESCRIPTION
**Pull request by hamflx**
try fix #3071

### CODE REVIEW

File: packages/core/src/helpers/getTextContentFromNodes.ts [hunk 1]
```diff
@@ -3,13 +3,15 @@ import { ResolvedPos } from 'prosemirror-model'
 export const getTextContentFromNodes = ($from: ResolvedPos, maxMatch = 500) => {
   let textBefore = ''
 
+  const to = $from.parentOffset
```
Comment (bdbch) [inline packages/core/src/helpers/getTextContentFromNodes.ts:6]: Just a quick one - since you're doing `to = $from` - would there be a more fitting variable name to explicitly tell what this is "to"? Otherwise this looks fine to me.

Comment (bdbch) [reply packages/core/src/helpers/getTextContentFromNodes.ts]: That sounds better. Thank you! I'd merge this afterwards.
