### PR TITLE
Fix InputRule regex matcher ignoring non-text leaflets in textBefore

### LINKED ISSUE #2806: Block level markdown shortcuts removes previous mention nodes
### What’s the bug you are facing?

Imagine the following content: `[mentionNode] *|`, where `|` represents the text cursor. Pressing `<space>`, will transform the whole paragraph into a bullet list:

firefox_8OQMmF1zHG

### Which browser was this experienced in? Are any special extensions installed?

All of them. No, just `StarterKit` and `Mention`.

### How can we reproduce the bug on our side?

Follow the steps in the GIF above with CodeSandbox below.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-issue-2806-oef3p6

### What did you expect to happen?

Block level markdown shortcuts, like the bullet list, should be ignored if there's something like a mention preceding it.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖 _(on behalf of Doist)_

### PR DESCRIPTION
**Pull request by bdbch**
This PR should fix #2806 

Currently non-text leaflets (which for example the Mention example is) this matcher is inserting space (` `) which would fit into the regex of the extension regex match strings.

I added a placeholder for this check resulting in non-text leafs being replaced with `%leaf%` which will stop those regex from returning true when a non-text leaf is used in front.

Since this function is not used for anything else but this check I think it's okay to use this %leaf% placeholder but I'm open for feedback or ideas how to solve this differently.

### CODE REVIEW

**Comment by bdbch** [comment]
I forced push a different solution proposed by @rfgamaral (thanks!).

We now include the textContent of non-text leafs & fallback to a `%leaf%` placeholder when no `renderText` function is provided.

File: packages/core/src/helpers/getTextContentFromNodes.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import { ResolvedPos } from 'prosemirror-model'
+
+export const getTextContentFromNodes = ($from: ResolvedPos<any>, maxMatch = 500) => {
```
Comment (rfgamaral) [inline packages/core/src/helpers/getTextContentFromNodes.ts:3]: Maybe export this in the `index.ts` file like all other helpers?

Comment (bdbch) [reply packages/core/src/helpers/getTextContentFromNodes.ts:3]: thanks, added
